### PR TITLE
Rename macOS.yml to Darwin.yml

### PR DESCRIPTION
**Pull request by ericraio**
This fails to execute on macOS because the os family name is Darwin and not macOS so the yml file never executes correctly.

ansible localhost -m ansible.builtin.setup | grep -i os_family
        "ansible_os_family": "Darwin",

### CODE REVIEW

**Comment by hurricanehrndz** [comment]
Thank you for the PR, I am reviewing it.

**Comment by ericraio** [comment]
bummer for the revert, did something break on linux?

**Comment by hurricanehrndz** [comment]
Nope that I am aware, but rather be safe

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by hurricanehrndz** [comment]
I should be able to get feedback soon, I got the tests going again

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by hurricanehrndz** [comment]
@ericraio merging fixes now that tests are backup

**Pull request merged**
