### PR TITLE
Fix undefined var

### PR DESCRIPTION
**Pull request by guenhter**
The main intention of this PR was to fix an "undefined variables" error. This is covered in the second commit. 
Then somehow I couldn't stop and made a few more changes to the role.
Maybe you can have a look and let me know what you think (it is easiest, to review this commit wise).

### CODE REVIEW

**Comment by guenhter** [comment]
Fixes https://github.com/hurricanehrndz/ansible-rustup/issues/8

**Comment by hurricanehrndz** [comment]
@guenhter there is a lot of changes here that fundamentally change the behaviour. Configuring the shell integration was optional, and thus should not be removed. I will have to get the test working before I can merge this to ensure base functionality is not effected.

**Comment by guenhter** [comment]
I removed the commit which gets rid of the shell integration.
Out of interest: What is the advantage of having the integration in this role when the rustup installs it anyway?

**Comment by hurricanehrndz** [comment]
Good question, I honestly don't remember. It was a long time ago. Perhaps it does need a revisit, I will need to get the tests working first though before I feel comfortable committing such a change. 

Taking a guess, I feel like I was evaluating Ansible for dotfile management, and I probably felt like those tasks assisted in some shape of form.

I have since than switch to Nix.

**Comment by hurricanehrndz** [comment]
PR looks good, I am going to give it the college try to get test working today, either which way I will merge by the end of the weekend.

**Comment by hurricanehrndz** [comment]
Thanks again for taking the time

**Comment by guenhter** [comment]
Any update on this?

**Comment by hurricanehrndz** [comment]
Thanks for the ping, I will merge it today

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by guenhter** [comment]
Thx

**Pull request merged**
